# Generated by Django 3.0.8 on 2020-07-06 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Category', models.IntegerField(default=0)),
                ('Description', models.CharField(blank=True, max_length=100)),
                ('StockIn', models.IntegerField(blank=True, default=0)),
                ('StockOut', models.IntegerField(blank=True, default=0)),
                ('Date', models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 11, 53, 39, 910638, tzinfo=utc), null=True)),
                ('ModifiedDate', models.DateField(blank=True, default=datetime.datetime(2020, 7, 6, 11, 53, 39, 911637, tzinfo=utc), null=True)),
            ],
        ),
    ]
