# Generated by Django 3.0.7 on 2020-07-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200706_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.IntegerField(default=0)),
                ('RawFile', models.CharField(max_length=200)),
                ('Description', models.CharField(blank=True, max_length=100)),
                ('Size', models.IntegerField(default=0)),
                ('Favorite', models.IntegerField(default=0)),
                ('Date', models.DateField(null=True)),
                ('ModifiedDate', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
